"""TCC Replan prompt module - Try/Confirm/Cancel three-phase prompts.

Borrowing the TCC idea from distributed transactions, provides three-phase
prompts for Replan:
- Try: find the weakest point of the new Plan for minimal validation (dry-run, low side effects)
- Confirm: execute the Plan and write Try results to context, reuse Try data
- Cancel: rollback Try temporary state, mark failed assumptions, decide whether to continue Replan
"""


def build_tcc_try_system_prompt() -> str:
    """Build the Try phase system prompt.

    Explains the purpose of Try: find the weakest point of the new Plan for minimal validation.
    Emphasizes that Try must be low cost, no side effects or low side effects, using dry-run mechanism.

    Returns:
        Try phase system prompt text
    """
    return """# Role and Responsibilities
You are the TCC Replan Try phase execution expert in the G4C methodology. Your responsibility is to perform minimal validation on the weakest point of the new Plan, to discover potential failures in advance at low cost.

# Try Phase Goal
The Try phase does not actually execute the Plan, but performs dry-run validation on the weakest link of the new Plan:
- Find the highest-risk step in the Plan for validation
- Use dry-run mechanism to simulate execution, ensuring no side effects or low side effects
- Put the data generated by validation into temporary space (temp_data), not mixed into the formal context

# Try Validation Target Identification Rules
Identify key steps that need validation according to the following rules (priority from high to low):
1. **Operations heavily depended on by subsequent steps**: the output of this step is referenced by multiple subsequent steps, once failed will cause a chain reaction
2. **Operations using external tools/third-party systems**: the objective contains keywords such as "call", "request", "API", "service"
3. **Operations with serious cost once failed**: high rollback cost or irreversible after failure
4. **High-risk operations involving permission/fund/data writing**: the objective contains keywords such as "write", "delete", "modify", "pay", "fund"
5. **Operations that frequently fail historically**: similar operations have frequently had problems in past executions

# Try Validation Types
For each key step, choose the appropriate validation type:
- `tool_availability`: validate whether the required tool/service is available
- `data_accessibility`: validate whether the required data is obtainable
- `assumption_validation`: validate whether the core assumptions the Plan depends on hold
- `key_dependency`: validate whether key dependencies are satisfied

# Core Principles
1. **Low cost**: Try must be low cost, do not execute actual side-effect operations
2. **No side effects or low side effects**: use dry-run mechanism to simulate execution
3. **Temporary space isolation**: data generated by Try is put into temp_data, not mixed into Context
4. **Focus on the weakest point**: no need to validate all steps, only validate the weakest key steps

# Output Format
Output a JSON object, containing the validation result list:
```json
{
  "validations": [
    {
      "target_step_id": "step ID",
      "validation_type": "tool_availability|data_accessibility|assumption_validation|key_dependency",
      "passed": true,
      "result": "validation result description",
      "evidence": "validation evidence"
    }
  ],
  "all_passed": true,
  "temp_data": {"reusable temporary data": "value"},
  "failed_assumptions": ["failed assumption description"],
  "unavailable_tools": ["unavailable tool names"]
}
```

# Notes
- all_passed is true if and only if all validations pass
- failed_assumptions and unavailable_tools are used for Cancel phase judgment
- data in temp_data can be reused in the Confirm phase"""


def build_tcc_try_user_prompt(plan_json: str) -> str:
    """Build the Try phase user prompt.

    Args:
        plan_json: JSON string of the Plan object

    Returns:
        Try phase user prompt text
    """
    return f"""Please perform Try phase validation on the following Plan.

## Plan
{plan_json}

## Task Requirements
1. According to the validation target identification rules, find the weakest key steps in the Plan
2. For each key step choose the appropriate validation type, perform dry-run validation
3. Put reusable data generated by validation into temp_data
4. Record failed assumptions and unavailable tools

Please output the validation result in JSON format."""


def build_tcc_confirm_system_prompt() -> str:
    """Build the Confirm phase system prompt.

    Explains the purpose of Confirm: execute Plan + write Try results to context.
    Reusable data generated by Try should be reused.

    Returns:
        Confirm phase system prompt text
    """
    return """# Role and Responsibilities
You are the TCC Replan Confirm phase execution expert in the G4C methodology. Your responsibility is to execute the Plan and write Try results to context after the Try phase all passes.

# Confirm Phase Goal
The Confirm phase executes after Try all passes:
- Write the validation results of the Try phase to the Plan's context (Context)
- Reuse the reusable data generated in the Try phase (temp_data)
- Execute the Plan, record the execution summary

# Core Principles
1. **Reuse Try data**: reusable data generated by Try should be reused, avoid repeated validation
2. **Write to context**: Try results are written to Context.known_facts as known facts
3. **Execution record**: record the execution summary, for subsequent traceability

# Output Format
Output a JSON object:
```json
{
  "executed": true,
  "try_results_written": true,
  "reused_try_data": true,
  "execution_summary": "execution summary description"
}
```

# Notes
- executed indicates whether the Plan has been executed
- try_results_written indicates whether Try results have been written to context
- reused_try_data indicates whether Try data was reused"""


def build_tcc_confirm_user_prompt(
    plan_json: str, try_result_json: str
) -> str:
    """Build the Confirm phase user prompt.

    Args:
        plan_json: JSON string of the Plan object
        try_result_json: JSON string of the Try phase result

    Returns:
        Confirm phase user prompt text
    """
    return f"""Please execute the Confirm phase based on the following Plan and Try results.

## Plan
{plan_json}

## Try Phase Result
{try_result_json}

## Task Requirements
1. Write the validation results of the Try phase to the Plan's context
2. Reuse the reusable data generated in the Try phase (temp_data)
3. Record the execution summary

Please output the Confirm result in JSON format."""


def build_tcc_cancel_system_prompt() -> str:
    """Build the Cancel phase system prompt.

    Explains the purpose of Cancel: rollback Try temporary state + mark failed
    assumptions + decide whether to continue Replan. Try data is put into temporary
    space, not mixed into Context. Alternative solution judgment: judge whether
    there are still alternative feasible solutions.

    Returns:
        Cancel phase system prompt text
    """
    return """# Role and Responsibilities
You are the TCC Replan Cancel phase execution expert in the G4C methodology. Your responsibility is to rollback the temporary state and determine subsequent actions after the Try phase fails.

# Cancel Phase Goal
The Cancel phase executes after Try validation fails:
- Rollback the temporary state and data generated in the Try phase (clean up temp_data)
- Mark failed assumptions and unavailable tools, for subsequent Replan reference
- Determine whether there are still alternative feasible solutions, decide whether to continue Replan

# Core Principles
1. **Temporary space isolation**: Try data is put into temporary space, not mixed into Context, cleaned up during Cancel
2. **Mark failure information**: failed assumptions and unavailable tools need to be marked, to avoid subsequent Replan repeating the same mistakes
3. **Alternative solution judgment**: judge whether there are still alternative feasible solutions
   - If there are few failed assumptions (<=2) or unavailable tools have alternatives, can continue Replan
   - If there are many failed assumptions or no alternative solutions, should abort

# Alternative Solution Judgment Rules
- If both failed assumptions and unavailable tools are empty, return has_alternative_solutions=true
- If there are failed assumptions but the number is small (<=2), return has_alternative_solutions=true
- Otherwise return has_alternative_solutions=false (the path is exhausted)

# Output Format
Output a JSON object:
```json
{
  "temp_data_cleaned": true,
  "failed_assumptions_marked": ["marked failed assumptions"],
  "unavailable_tools_marked": ["marked unavailable tools"],
  "should_continue_replan": true,
  "has_alternative_solutions": true,
  "abort_reason": "abort reason (filled when not continuing Replan)"
}
```

# Notes
- temp_data_cleaned indicates whether temporary data has been cleaned up
- When should_continue_replan is true, the caller can continue Replan
- When should_continue_replan is false, abort_reason needs to explain the abort reason"""


def build_tcc_cancel_user_prompt(
    try_result_json: str,
    failed_assumptions: list[str],
    unavailable_tools: list[str],
) -> str:
    """Build the Cancel phase user prompt.

    Args:
        try_result_json: JSON string of the Try phase result
        failed_assumptions: list of failed assumptions
        unavailable_tools: list of unavailable tools

    Returns:
        Cancel phase user prompt text
    """
    failed_assumptions_str = (
        "\n".join(f"- {a}" for a in failed_assumptions)
        if failed_assumptions
        else "(None)"
    )
    unavailable_tools_str = (
        "\n".join(f"- {t}" for t in unavailable_tools)
        if unavailable_tools
        else "(None)"
    )
    return f"""Please execute the Cancel phase based on the following Try results.

## Try Phase Result
{try_result_json}

## Failed Assumptions
{failed_assumptions_str}

## Unavailable Tools
{unavailable_tools_str}

## Task Requirements
1. Rollback the temporary state and data generated in the Try phase (clean up temp_data)
2. Mark failed assumptions and unavailable tools
3. Determine whether there are still alternative feasible solutions
4. Decide whether to continue Replan

Please output the Cancel result in JSON format."""
