"""Replan data model - controlled correction mechanism.

Replan is the core implementation of Correction, defined as "during execution, based on new Goal, Context, Choice,
and Checkpoint results, performing controlled correction of the original plan".

Keywords: during execution, new information, controlled correction.

This module defines Replan-related control info, judgment results, step change records and execution results.
"""

from enum import Enum

from pydantic import BaseModel, Field

from xtao.models.plan import Plan


class ReplanTrigger(str, Enum):
    """Replan trigger timing type.

    - TOOL_FAILURE: tool call failure (non-transient)
    - CONTEXT_CHANGE: context changed (user adds constraints or supplements information)
    - ASSUMPTION_VIOLATION: assumption violated (checkpoint not passed, indicating original Plan assumptions are incorrect)
    """

    TOOL_FAILURE = "tool_failure"
    CONTEXT_CHANGE = "context_change"
    ASSUMPTION_VIOLATION = "assumption_violation"


class ReplanGranularity(str, Enum):
    """Replan granularity.

    - STEP: current step Replan, retains previously completed steps
    - PARTIAL: partial Replan, re-plans from a specified rollback step
    - GLOBAL: global Replan, generates a brand new Plan from scratch
    """

    STEP = "step"
    PARTIAL = "partial"
    GLOBAL = "global"


class ReplanInfo(BaseModel):
    """Replan control info.

    Used to limit the number of Replans, avoiding infinite loops.
    """

    max_replan_total: int = Field(default=3, description="Maximum allowed Replan count")
    used_replan_total: int = Field(default=0, description="Used Replan count")


class ReplanJudgment(BaseModel):
    """Replan judgment result.

    Generated by code judgment or LLM judgment, decides whether Replan is needed and how to Replan.
    """

    needs_replan: bool = Field(description="Whether Replan is needed")
    trigger: ReplanTrigger | None = Field(
        default=None, description="Trigger timing type"
    )
    reason: str = Field(default="", description="Judgment reason")
    evidence: str = Field(default="", description="Judgment evidence")
    granularity: ReplanGranularity | None = Field(
        default=None, description="Suggested Replan granularity"
    )
    rollback_step_id: str | None = Field(
        default=None, description="Rollback target step ID for partial Replan"
    )


class StepChange(BaseModel):
    """Step change record.

    Records the change status of each step after Replan, all changes must be evidence-based.
    """

    step_id: str = Field(description="Step ID")
    reason: str = Field(default="", description="Change reason (evidence-based)")
    change_type: str = Field(
        description="Change type: retained | modified | removed"
    )
    modification_detail: str = Field(
        default="", description="Modification details, only valid when modified"
    )


class ReplanResult(BaseModel):
    """Replan execution result.

    Contains step change classification (retained/modified/removed), new Plan and updated control info.
    """

    retained_steps: list[StepChange] = Field(
        default_factory=list, description="Retained steps and reasons"
    )
    modified_steps: list[StepChange] = Field(
        default_factory=list, description="Modified steps and reasons"
    )
    removed_steps: list[StepChange] = Field(
        default_factory=list, description="Removed steps and reasons"
    )
    new_plan: Plan | None = Field(
        default=None, description="New Plan after Replan"
    )
    replan_info: ReplanInfo = Field(
        default_factory=ReplanInfo, description="Updated Replan control info"
    )
